.PHONY: clean

default: all

all: mkl openblas naive naive2 naive3 cblas

mkl: mkl.c
	gcc mkl.c -Wl,--start-group /opt/intel/mkl/lib/intel64/libmkl_intel_ilp64.a /opt/intel/mkl/lib/intel64/libmkl_sequential.a /opt/intel/mkl/lib/intel64/libmkl_core.a -Wl,--end-group -lpthread -lm -ldl -DMKL_ILP64 -m64 -I/opt/intel/mkl/include -o mkl

openblas: openblas.c
	gcc openblas.c -I/mnt/e/Downloads/OpenBLAS-0.2.20/ -L/mnt/e/Downloads/OpenBLAS-0.2.20/ -lopenblas -o openblas

cblas: cblas.c
	gcc cblas.c -lcblas -lgfortran cblas_LINUX.a libblas.a -o cblas /mnt/e/Downloads/CBLAS/testing/c_d3chke.o /mnt/e/Downloads/CBLAS/testing/auxiliary.o /mnt/e/Downloads/CBLAS/testing/c_xerbla.o

naive: naive.c
	gcc naive.c -o naive

naive2: naive2.c
	gcc naive2.c -o naive2

naive3: naive3.c
	gcc naive3.c -o naive3

clean:
	rm -f mkl openblas naive
